name: Pablo Gándara-Pizá
favicon: null
layout_spectrum: 0.1765667295549065
typography_spectrum: 0.5018848301842809
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8878412388730794
  lightness: 0.76060132519342
  saturation: 0.6747294212691486
  rhythmicContrast: 0.562185371061787
purpose: []
